# --------------------------------------------------------------------------------------------------------------------------------------------

spring.application.name=demo

# ==============================================================
# 1. BINDING SU LOCALHOST (SICUREZZA)
# ==============================================================
# L'app ascolta internamente sulla 9090
server.port=9090
# IMPORTANTE: Blinda l'app. Accetta connessioni SOLO da Nginx (stesso PC)
server.address=127.0.0.1

# ==============================================================
# GESTIONE PROXY
# ==============================================================
server.forward-headers-strategy=native

management.info.env.enabled=true
management.endpoints.web.exposure.include=health,info
info.app.name=IngFlix
info.app.description=Lo Streaming a casa tua

spring.security.user.name=DISABLED
spring.security.user.password=DISABLED

# ==============================================================
# DATABASE
# ==============================================================
# Il database è sulla stessa macchina, quindi localhost va bene
spring.datasource.url=jdbc:mysql://localhost:3306/DB?allowMultiQueries=true&sslMode=VERIFY_CA&trustCertificateKeyStoreUrl=file:pathtoTruststore/mysql-truststore.jks&trustCertificateKeyStorePassword=changeit&serverTimezone=UTC

#Accetta query multiple-->Vulnerabilità SQL injection
# spring.datasource.url=jdbc:mysql://localhost:3306/system_security?allowMultiQueries=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect


# 1. Redirect URI:
spring.security.oauth2.client.registration.keycloak.redirect-uri=https://localhost/login/oauth2/code/keycloak

# 2. Issuer URI:
# L'indirizzo pubblico di Keycloak (tramite Nginx)
spring.security.oauth2.client.provider.keycloak.issuer-uri=https://localhost:8443/realms/Ing.Flix

spring.security.oauth2.client.provider.keycloak.user-name-attribute=preferred_username


# ==============================================================
# CONFIGURAZIONE VAULT
# ==============================================================
spring.cloud.vault.uri=http://127.0.0.1:8200
spring.cloud.vault.authentication=APPROLE

# Importa i segreti
spring.config.import=vault://secret/my-webapp/keycloak,vault://secret/my-webapp/database

# Config Keycloak Client
spring.security.oauth2.client.registration.keycloak.client-id=Flix
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.scope=openid
spring.security.oauth2.client.registration.keycloak.client-secret=${client_secret}

# Config KV Vault
spring.cloud.vault.kv.backend=secret
spring.cloud.vault.kv.enabled=true
spring.cloud.compatibility-verifier.enabled=false

# Credenziali DB
spring.datasource.username=${db_username}
spring.datasource.password=${db_password}

# ==============================================================
# SICUREZZA SESSIONE
# ==============================================================
# # Il cookie viaggia SOLO su HTTPS
# server.servlet.session.cookie.secure=true
# # Il cookie non è leggibile da JavaScript (protegge da attacchi XSS)
# server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.http-only=false
# # Il cookie non viene inviato da siti terzi (protegge da CSRF)
# server.servlet.session.cookie.same-site=strict
# # Opzionale: Dai un nome personalizzato al cookie per non dire "Sono Spring Boot" (default è JSESSIONID)
# server.servlet.session.cookie.name=APPSESSIONID

# server.servlet.session.timeout=30m


#--------------------------------------------------------------------------------
#Proprietà per informazioni tramite sql injection, facciamo stampare tutti i messaggi di errore con tutte le info
# Mostra il messaggio dell'eccezione nel JSON di risposta
server.error.include-message=always

# (Opzionale) Mostra tutto lo stack trace nel browser
server.error.include-stacktrace=always

# Percorso del file di log
logging.file.name=pthtoapplication.log

# Livello di dettaglio
logging.level.root=INFO
logging.level.org.springframework.web=INFO
# logging.level.com.tuopacchetto=DEBUG

# Pattern del log (per analisi migliore)
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# Log dettagliati del DispatcherServlet
logging.level.org.springframework.web.servlet.DispatcherServlet=INFO

# Se usi database - log delle query SQL
logging.level.org.hibernate.SQL=INFO
# logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Log di Keycloak/Security (se usi autenticazione)
logging.level.org.springframework.security=INFO